[package]
name = "noughts_and_crosses"
version = "0.1.0"
authors = ["soakins <68757318+soakins@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19.0"
